package main

import (
	"encoding/json"
	"os"
	"path/filepath"
	"time"

	"sign-extension/tools/pkg/contracts/sign"

	"github.com/pkg/errors"
)

// The web demo needs one thing from this command that the chain does not carry:
// the attestation request body each policy is bound to. The chain stores only its
// hash, and a hash cannot be turned back into the request the FDC verifier has to
// be handed.
//
// Publishing it is safe by design. The request body is a public weather query
// (a URL, a date window, a jq filter), it is the same value already hashed into
// policyTriggerRequestHash, and the binding is write once, so knowing it lets
// anyone reproduce the attestation and nobody repoint the policy. The insurer's
// model is not in here and has no route into this file.
//
// It is written from the same policyCatalog entry the policy was created from, so
// the page and the chain cannot drift apart silently. The page checks anyway: it
// asks InstructionSender.triggerRequestHash for the hash of what it holds and
// compares that against policyTriggerRequestHash on chain, and says so loudly
// when the two disagree.

// webRequestBody mirrors IWeb2Json.RequestBody with the field names the FDC
// verifier's JSON API uses, so the page can post it to prepareRequest unchanged.
type webRequestBody struct {
	URL           string `json:"url"`
	HTTPMethod    string `json:"httpMethod"`
	Headers       string `json:"headers"`
	QueryParams   string `json:"queryParams"`
	Body          string `json:"body"`
	PostProcessJq string `json:"postProcessJq"`
	AbiSignature  string `json:"abiSignature"`
}

type webPolicy struct {
	Name        string         `json:"name"`
	PolicyID    string         `json:"policyId"`
	Description string         `json:"description"`
	Latitude    string         `json:"latitudeDeg"`
	Longitude   string         `json:"longitudeDeg"`
	StartDate   string         `json:"startDate"`
	EndDate     string         `json:"endDate"`
	RequestBody webRequestBody `json:"requestBody"`
	CreatedAt   time.Time      `json:"createdAt"`
}

type webPolicyFile struct {
	Note     string      `json:"note"`
	Policies []webPolicy `json:"policies"`
}

const webPolicyNote = "Generated by aegis register-model --web-config. " +
	"Public data only: the attestation request each policy is bound to, never a model parameter. " +
	"The page verifies every entry against policyTriggerRequestHash on chain before offering it."

// upsertWebPolicy records one policy in the file the web demo reads, replacing an
// entry with the same policy id and otherwise appending.
//
// Appending rather than replacing the file matters: a policy settles exactly once
// and then closes, so a list a judge can try has to accumulate several of them.
func upsertWebPolicy(path string, record *policyRecord, template policyTemplate) error {
	requestBody, err := template.feed.RequestBody()
	if err != nil {
		return errors.Errorf("building the attestation request for the web config: %s", err)
	}

	file := webPolicyFile{Note: webPolicyNote}
	raw, err := os.ReadFile(path)
	switch {
	case err == nil:
		if unmarshalErr := json.Unmarshal(raw, &file); unmarshalErr != nil {
			return errors.Errorf("parsing %s: %s", path, unmarshalErr)
		}
		file.Note = webPolicyNote
	case !os.IsNotExist(err):
		return errors.Errorf("reading %s: %s", path, err)
	}

	entry := webPolicy{
		Name:        record.Name,
		PolicyID:    record.PolicyID,
		Description: template.description,
		Latitude:    template.feed.LatitudeDeg,
		Longitude:   template.feed.LongitudeDeg,
		StartDate:   template.feed.StartDate,
		EndDate:     template.feed.EndDate,
		RequestBody: toWebRequestBody(requestBody),
		CreatedAt:   record.CreatedAt,
	}

	replaced := false
	for i := range file.Policies {
		if file.Policies[i].PolicyID == entry.PolicyID {
			file.Policies[i] = entry
			replaced = true
			break
		}
	}
	if !replaced {
		file.Policies = append(file.Policies, entry)
	}

	encoded, err := json.MarshalIndent(file, "", "  ")
	if err != nil {
		return errors.Errorf("encoding the web config: %s", err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return errors.Errorf("creating %s: %s", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, append(encoded, '\n'), 0o644); err != nil {
		return errors.Errorf("writing %s: %s", path, err)
	}

	return nil
}

// readWebPolicies returns the policies the web demo offers, or nothing at all if
// the file has never been written. A missing file is not an error: a deployment
// that only ever used the CLI has no web config, and reregister-all still has
// the state file to work from.
func readWebPolicies(path string) ([]webPolicy, error) {
	raw, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, errors.Errorf("reading %s: %s", path, err)
	}

	var file webPolicyFile
	if err := json.Unmarshal(raw, &file); err != nil {
		return nil, errors.Errorf("parsing %s: %s", path, err)
	}
	return file.Policies, nil
}

func toWebRequestBody(rb sign.IWeb2JsonRequestBody) webRequestBody {
	return webRequestBody{
		URL:           rb.Url,
		HTTPMethod:    rb.HttpMethod,
		Headers:       rb.Headers,
		QueryParams:   rb.QueryParams,
		Body:          rb.Body,
		PostProcessJq: rb.PostProcessJq,
		AbiSignature:  rb.AbiSignature,
	}
}
